[package]
name = "user_rust"
version = "0.1.0"
authors = ["John Sigvald Skauge <johnsigvaldskauge@tv2.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.4", features =  ["postgres", "numeric", "uuid", "quickcheck", "serde_json", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0.116", features = ["derive"] }
sha2 = "0.9.1"
dotenv = "0.15.0"
