version: "3.8"
services:
  postgres:
    image: postgres:13.1
    container_name: postgres
    volumes:
      - /tmp/postgres_data_users/:/var/lib/postgresql/data
      - ${PWD}/db/:/tmp/
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: user
      POSTGRES_PASSWORD: user
    networks:
      - test
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - test
  # backend:
  #   image: ghcr.io/modulus/user-rust:latest     
  #   container_name: backend
  #   ports: 
  #     - "5000:8080"
  #   environment:
  #     DATABASE_URL: postgres://user:user@postgres/user
  #   restart: always
  #   networks:
  #     - test

networks:
  test:
    driver: bridge

