version: "3.8"
services:
  postgres:
    image: postgres:13.0
    container_name: postgres
    volumes:
      - /tmp/postgres_data_users/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: user
      POSTGRES_PASSWORD: user
    networks:
      - test
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - test

networks:
  test:
    driver: bridge

