name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://user:user@postgres/user

jobs:
  build:
    runs-on: ubuntu-latest
    container: rust:1.47-buster
    services:
      postgres:
        image: postgres:13.0
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: user
          POSTGRES_DB: user
          POSTGRES_PASSWORD: user
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Install diesel
      run: cargo install diesel_cli
    - name: Prepare database
      run: diesel migration run
    - name: Run tests
      run: cargo test --verbose
    - name: Build docker container
      run: docker build . --file Dockerfile --tag user-rust:latest
